redirect from login.gov -> www.login.gov
cloud-gov/pages-redirects pull request #186
Opened 2021-11-30 14:33 UTC by jmdembe

This PR creates a redirect from `login.gov` to `www.login.gov`

2021-12-01 18:09 UTC, amirbey commented on templates/_federalist-redirects.njk
> +  server_name login.gov;
```suggestion
  server_name login.gov;
  add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
```

2021-12-01 18:10 UTC, amirbey commented on templates/_federalist-redirects.njk
> +  server_name login.gov;
hsts requirement was previously fulfilled for login.gov by fedralist-proxy server
https://github.com/18F/federalist-proxy/pull/108

2021-12-01 18:35 UTC, amirbey commented on pages.yml
> +- www.login.gov
```suggestion
```

2021-12-01 20:07 UTC, amirbey requested changes
hi @jmdembe  ... i've made a few suggestions before merging ... pls review

2023-05-05 15:56 UTC, aduth commented
@jmdembe Are we still wanting this? I notice this pull request is draft but there are some recent commits.

2023-05-08 12:36 UTC, jmdembe commented
> @jmdembe Are we still wanting this? I notice this pull request is draft but there are some commits more recent than the last round of review.

This can be closed. This was resolved between the Cloud.gov team and DevOps instead of through this ticket.

2023-05-08 12:36 UTC, closed without merging